[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyscaleS3"
version = "1.0.0"
description = "Description of library"
readme = "README.md"
authors = [ "Drayer Sivertsen <drayer.sivertsen@wsu.edu>", "Nathan Marugame <nathan.marugame@wsu.edu>", "Killian Griffin <killian.griffin@wsu.edu>" ]
license = { **License file** }
classifiers = [ **List of classifiers** ]
keywords = [ **List of keywords** ]
requires-python = ">=3.9"
dependencies = [ **List of necessary dependencies** ]
# ">= version" specifies the lowest version needed for the package
# "; python_version < version" specifies the dependency is only needed under a specified python version


[project.optional-dependencies]
dev = [ **List of optional dependencies** ]

[project.urls]
Homepage = "https://github.com/EMCECS/objectscale-s3-client-python"

[project.scripts]
<command_line_function> = <script call>
...